/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package swing;

import clases.Cliente;

import java.awt.BorderLayout;
import java.io.*;
import java.security.InvalidKeyException;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import javax.crypto.*;
import javax.swing.*;

/**
 *
 * @author leiii
 */
public class InicioSesion extends javax.swing.JPanel {
    JPanel pane;
    JFrame ventana;
    private Cipher cipher;
    ObjectOutputStream oos;
    ObjectInputStream ois;
    SecretKey key;

    /**
     * Creates new form InicioSesion
     */
    public InicioSesion(JFrame ventana, JPanel pane, ObjectOutputStream oos, ObjectInputStream ois, SecretKey key) {
        initComponents();
        this.oos = oos;
        this.ois = ois;
        this.key = key;
        this.pane = pane;
        this.ventana = ventana;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        usuario = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        botonRegistrar = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        botonIniciarSesion = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        contrasena = new javax.swing.JPasswordField();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("INICIAR SESIÓN");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel2.setText("USUARIO");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        usuario.setBorder(null);
        add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 350, -1));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 350, 10));

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel3.setText("CONTRASEÑA");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 350, 10));

        botonRegistrar.setBackground(new java.awt.Color(153, 0, 102));
        botonRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonRegistrarMousePressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Registrarse");

        javax.swing.GroupLayout botonRegistrarLayout = new javax.swing.GroupLayout(botonRegistrar);
        botonRegistrar.setLayout(botonRegistrarLayout);
        botonRegistrarLayout.setHorizontalGroup(
            botonRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botonRegistrarLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel4)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        botonRegistrarLayout.setVerticalGroup(
            botonRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botonRegistrarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(botonRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, 120, 30));

        botonIniciarSesion.setBackground(new java.awt.Color(153, 0, 102));
        botonIniciarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonIniciarSesionMousePressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Iniciar sesión");

        javax.swing.GroupLayout botonIniciarSesionLayout = new javax.swing.GroupLayout(botonIniciarSesion);
        botonIniciarSesion.setLayout(botonIniciarSesionLayout);
        botonIniciarSesionLayout.setHorizontalGroup(
            botonIniciarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        botonIniciarSesionLayout.setVerticalGroup(
            botonIniciarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botonIniciarSesionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap())
        );

        add(botonIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 370, 120, 30));

        contrasena.setBorder(null);
        add(contrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 350, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void botonRegistrarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegistrarMousePressed
        RegistrarUsuario frame = new RegistrarUsuario(ventana, pane, oos, ois, key);
        frame.setSize(490,450);
        frame.setLocation(0,0);
        pane.removeAll();
        pane.add(frame, BorderLayout.CENTER);
        pane.revalidate();
        pane.repaint();
    }//GEN-LAST:event_botonRegistrarMousePressed

    private void botonIniciarSesionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonIniciarSesionMousePressed
        //comprovamos que los campos tienen datos
        if (!usuario.getText().isBlank() && !contrasena.getText().isBlank()) {
            try {
                ByteArrayOutputStream bos = new ByteArrayOutputStream();
                ObjectOutputStream oosbytes = new ObjectOutputStream(bos);
                oos.writeObject(1);
                //hasheamos la contraseña
                MessageDigest md = MessageDigest.getInstance("SHA");
                byte[] contrasenaBytes = contrasena.getText().getBytes();
                md.update(contrasenaBytes);
                byte[] resumen = md.digest();
                String hashContrasena = new String(resumen);
                //creamos un objeto con todos los datos del inicio de sesion
                Cliente cliente = new Cliente(usuario.getText(), hashContrasena);
                //lo comvertimos a bytes
                oosbytes.writeObject(cliente);
                oosbytes.flush();
                byte[] userbytes = bos.toByteArray();
                //recogemos la clave
                cipher = Cipher.getInstance("DES");
                //configuramos modo encriptar
                cipher.init(Cipher.ENCRYPT_MODE, key);
                byte[] clienteCifrado = cipher.doFinal(userbytes);
                //enviamos objeto cifrado
                oos.writeObject(clienteCifrado);
                //recogemos login
                cipher.init(Cipher.DECRYPT_MODE, key);
                clienteCifrado = (byte[]) ois.readObject();
                userbytes = cipher.doFinal(clienteCifrado);
                ByteArrayInputStream bis = new ByteArrayInputStream(userbytes);
                ObjectInputStream oisbytes = new ObjectInputStream(bis);
                cliente = (Cliente) oisbytes.readObject();
                bis.close();
                oisbytes.close();
                if (cliente.isAcierto()) {
                    new VentanaPrincipal(ois, oos, key).setVisible(true);
                    ventana.dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "Usuario o contraseña incorrectos");
                }
            } catch (IOException | ClassNotFoundException ex) {
                JOptionPane.showMessageDialog(null, "Ha surgido un error con el servidor");
                ex.printStackTrace();
            } catch (NoSuchPaddingException | IllegalBlockSizeException | BadPaddingException ex) {
                JOptionPane.showMessageDialog(null, "Ha surgido un error inesperado");
            } catch (NoSuchAlgorithmException ex) {
                JOptionPane.showMessageDialog(null, "No se ha especificado el algoritmo de encriptacion");
            } catch (InvalidKeyException ex) {
                JOptionPane.showMessageDialog(null, "La llave no es correcta");
            }
        } else {
            JOptionPane.showMessageDialog(null, "ERROR tienes que rellenar todos los campos.");
        }
    }//GEN-LAST:event_botonIniciarSesionMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel botonIniciarSesion;
    private javax.swing.JPanel botonRegistrar;
    private javax.swing.JPasswordField contrasena;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField usuario;
    // End of variables declaration//GEN-END:variables
}
