/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package swing;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.security.InvalidKeyException;
import java.security.NoSuchAlgorithmException;
import java.util.List;
import javax.crypto.*;
import javax.swing.*;
import javax.swing.border.EmptyBorder;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

import clases.Cuenta;
import scrollbar.ScrollBarCustom;
import table.TableHeader;

/**
 *
 * @author leiii
 */
public class MisCuentas extends javax.swing.JPanel {
    String[] nombreColumnas = {"Número de cuenta", "Titular", "Saldo"};
    JPanel panel;
    private SecretKey key;
    private ObjectOutputStream oos;
    private ObjectInputStream ois;
    
    /**
     * Creates new form MisCuentas
     */
    public MisCuentas(JPanel panel, ObjectInputStream ois, ObjectOutputStream oos, SecretKey key) {
        initComponents();
        this.key = key;
        this.oos = oos;
        this.ois = ois;
        this.panel = panel;

        //Le damos otro estilo a la tabla
        tablaMisCuentas.setShowHorizontalLines(true);
        tablaMisCuentas.setGridColor(new Color(230,230,230));
        tablaMisCuentas.setRowHeight(40);
        tablaMisCuentas.getTableHeader().setReorderingAllowed(true);
        tablaMisCuentas.getTableHeader().setDefaultRenderer(new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                TableHeader header = new TableHeader(value + "");
                if(column==nombreColumnas.length){
                    header.setHorizontalAlignment(JLabel.CENTER);
                }
                return header;
            }
       });

       jScrollPane1.getViewport().setBackground(Color.WHITE);
       jScrollPane1.setVerticalScrollBar(new ScrollBarCustom());
       fixtable(jScrollPane1);

       //Cargamos los datos en la tabla
       cargarDatos();
    }
    
    public void fixtable(JScrollPane scroll) {
        scroll.getViewport().setBackground(Color.WHITE);
        scroll.setVerticalScrollBar(new ScrollBarCustom());
        JPanel p = new JPanel();
        scroll.setCorner(JScrollPane.UPPER_RIGHT_CORNER, p);
        scroll.setBorder(new EmptyBorder(5, 10, 5, 10));
    }

    public void cargarDatos() {
        try {
            //mandamos la opcion que queremos
            oos.writeObject(1);
            Cipher desCipher = Cipher.getInstance("DES");
            desCipher.init(Cipher.DECRYPT_MODE, key);
            //recuperamos la lista de cuentas del cliente encriptadas
            byte[] cuentasCifradas = (byte[]) ois.readObject();
            byte[] cuentasBytes = desCipher.doFinal(cuentasCifradas);
            ByteArrayInputStream bis = new ByteArrayInputStream(cuentasBytes);
            ObjectInputStream oisbytes = new ObjectInputStream(bis);
            List<Cuenta> cuentas = (List<Cuenta>) oisbytes.readObject();
            bis.close();
            oisbytes.close();
            //cargamos las cuentas en la tabla para mostrarlas
            int cantidad = cuentas.size();
            String[][] d = new String[cantidad][2];
            String[] nombreColumnas = {"Número de cuenta", "Saldo"};
            for (int i = 0; i < cuentas.size(); i++) {
                d[i][0] = String.valueOf(cuentas.get(i).getNumeroCuenta());
                d[i][1] = String.valueOf(cuentas.get(i).getSaldo());
            }
            tablaMisCuentas.setModel(new DefaultTableModel(d, nombreColumnas));
        } catch (IOException | BadPaddingException | IllegalBlockSizeException | NoSuchPaddingException e) {
            JOptionPane.showMessageDialog(null, "Ha ocurrido un error inesperado");
        } catch (NoSuchAlgorithmException e) {
            JOptionPane.showMessageDialog(null, "No se ha especificado el algoritmo");
        } catch (InvalidKeyException e) {
            JOptionPane.showMessageDialog(null, "La llave no es correcta");
        } catch (ClassNotFoundException e) {
            JOptionPane.showMessageDialog(null, "No se han podido cargar los datos");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaMisCuentas = new javax.swing.JTable();
        botonVer = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("MIS CUENTAS");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        tablaMisCuentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaMisCuentas);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 90, 482, 270));

        botonVer.setBackground(new java.awt.Color(153, 0, 102));
        botonVer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonVerMousePressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Ver Información");

        javax.swing.GroupLayout botonVerLayout = new javax.swing.GroupLayout(botonVer);
        botonVer.setLayout(botonVerLayout);
        botonVerLayout.setHorizontalGroup(
            botonVerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botonVerLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        botonVerLayout.setVerticalGroup(
            botonVerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botonVerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap())
        );

        add(botonVer, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 380, 140, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void botonVerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonVerMousePressed
        InfoCuenta frame = new InfoCuenta(panel, ois, oos, key);
        frame.setSize(560,450);
        frame.setLocation(0,0);
        panel.removeAll();
        panel.add(frame, BorderLayout.CENTER);
        panel.revalidate();
        panel.repaint();
    }//GEN-LAST:event_botonVerMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel botonVer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaMisCuentas;
    // End of variables declaration//GEN-END:variables
}
