/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package swing;

/**
 *
 * @author leiii
 */
public class MisDatos extends javax.swing.JPanel {

    /**
     * Creates new form MisDatos
     */
    public MisDatos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        apellido = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        contrasena = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        usuario = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        email = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        edad = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/user.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, -1, -1));

        jLabel2.setText("Nombre:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, -1, -1));

        jLabel3.setText("Apellido:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, -1, -1));

        jLabel4.setText("Edad:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, -1, -1));

        jLabel5.setText("Email:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, -1, -1));

        jLabel6.setText("Usuario:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, -1, -1));

        jLabel7.setText("Contraseña:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 390, -1, -1));

        nombre.setEditable(false);
        nombre.setBackground(new java.awt.Color(255, 255, 255));
        nombre.setBorder(null);
        add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 170, -1));

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 170, 10));

        apellido.setEditable(false);
        apellido.setBackground(new java.awt.Color(255, 255, 255));
        apellido.setBorder(null);
        add(apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 170, -1));

        jSeparator3.setBackground(new java.awt.Color(255, 255, 255));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, 170, 10));

        contrasena.setEditable(false);
        contrasena.setBackground(new java.awt.Color(255, 255, 255));
        contrasena.setBorder(null);
        add(contrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 390, 170, -1));

        jSeparator4.setBackground(new java.awt.Color(255, 255, 255));
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 410, 170, 10));

        usuario.setEditable(false);
        usuario.setBackground(new java.awt.Color(255, 255, 255));
        usuario.setBorder(null);
        add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 340, 170, -1));

        jSeparator5.setBackground(new java.awt.Color(255, 255, 255));
        add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, 170, 10));

        email.setEditable(false);
        email.setBackground(new java.awt.Color(255, 255, 255));
        email.setBorder(null);
        add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, 170, -1));

        jSeparator6.setBackground(new java.awt.Color(255, 255, 255));
        add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, 170, 10));

        edad.setEditable(false);
        edad.setBackground(new java.awt.Color(255, 255, 255));
        edad.setBorder(null);
        add(edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 170, -1));

        jSeparator7.setBackground(new java.awt.Color(255, 255, 255));
        add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, 170, 10));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellido;
    private javax.swing.JTextField contrasena;
    private javax.swing.JTextField edad;
    private javax.swing.JTextField email;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField usuario;
    // End of variables declaration//GEN-END:variables
}
