/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package swing;

import clases.Cuenta;
import clases.Transferencia;

import javax.crypto.*;
import javax.swing.*;
import java.awt.*;
import java.io.*;
import java.security.InvalidKeyException;
import java.security.NoSuchAlgorithmException;
import java.util.Date;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 *
 * @author leiii
 */
public class NuevaTransferencia extends javax.swing.JPanel {

    JPanel panel;
    private SecretKey key;
    private ObjectInputStream ois;
    private ObjectOutputStream oos;

    /**
     * Creates new form Transferencias
     */
    public NuevaTransferencia(JPanel panel, SecretKey key, ObjectInputStream ois, ObjectOutputStream oos) {
        initComponents();
        this.key = key;
        this.ois = ois;
        this.oos = oos;
        this.panel = panel;

        try {
            //mandamos la opcion para cargar el combobox con datos
            oos.writeObject(2);
            //recuperamos la lista de cuentas y la cargamos en el combobox
            byte[] cuentasEncriptadas = (byte[]) ois.readObject();
            Cipher desCipher = Cipher.getInstance("DES");
            desCipher.init(Cipher.DECRYPT_MODE, key);
            byte[] cuentasBytes = desCipher.doFinal(cuentasEncriptadas);
            ByteArrayInputStream bis = new ByteArrayInputStream(cuentasBytes);
            ObjectInputStream oisbytes = new ObjectInputStream(bis);
            List<Cuenta> cuentas = (List<Cuenta>) oisbytes.readObject();
            bis.close();
            oisbytes.close();
            //Mostramos todas las cuentas guardadas en la base de datos
            for (Cuenta cuenta : cuentas) {
                cuentaRemitente.addItem(cuenta.getNumeroCuenta());
            }
            //Damos a la fecha el valor de hoy
            fecha.setText(String.valueOf(new Date()));

        } catch (NoSuchPaddingException | IllegalBlockSizeException | IOException | BadPaddingException e) {
            JOptionPane.showMessageDialog(null, "Ha ocurrido un error inesperado");
        } catch (NoSuchAlgorithmException e) {
            JOptionPane.showMessageDialog(null, "No se ha especificado el algoritmo");
        } catch (InvalidKeyException e) {
            JOptionPane.showMessageDialog(null, "La llave no es correcta");
        } catch (ClassNotFoundException e) {
            JOptionPane.showMessageDialog(null, "No se han podido cargar los datos");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonRealizarTransferencia = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        botonLimpiar = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cantidad = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        fecha = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        cuentaRemitente = new javax.swing.JComboBox<>();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        concepto = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        cuentaDestinataria = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonRealizarTransferencia.setBackground(new java.awt.Color(153, 0, 102));
        botonRealizarTransferencia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonRealizarTransferenciaMousePressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Realizar transferencia");

        javax.swing.GroupLayout botonRealizarTransferenciaLayout = new javax.swing.GroupLayout(botonRealizarTransferencia);
        botonRealizarTransferencia.setLayout(botonRealizarTransferenciaLayout);
        botonRealizarTransferenciaLayout.setHorizontalGroup(
            botonRealizarTransferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botonRealizarTransferenciaLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel5)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        botonRealizarTransferenciaLayout.setVerticalGroup(
            botonRealizarTransferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botonRealizarTransferenciaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap())
        );

        add(botonRealizarTransferencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, 180, 30));

        botonLimpiar.setBackground(new java.awt.Color(153, 0, 102));
        botonLimpiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonLimpiarMousePressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Limpiar");

        javax.swing.GroupLayout botonLimpiarLayout = new javax.swing.GroupLayout(botonLimpiar);
        botonLimpiar.setLayout(botonLimpiarLayout);
        botonLimpiarLayout.setHorizontalGroup(
            botonLimpiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botonLimpiarLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel6)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        botonLimpiarLayout.setVerticalGroup(
            botonLimpiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botonLimpiarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(botonLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, 120, 30));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel1.setText("Cuenta destinataria:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 150, -1, -1));

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("TRANSFERENCIA");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 40, 540, -1));

        jLabel3.setText("Cantidad:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 250, -1, -1));

        cantidad.setBorder(null);
        add(cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, 170, -1));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 190, 10));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, 170, 10));

        jLabel4.setText("Fecha:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 300, -1, -1));

        fecha.setEditable(false);
        fecha.setBackground(new java.awt.Color(255, 255, 255));
        fecha.setBorder(null);
        add(fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, 170, -1));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, 170, 10));

        jLabel7.setText("Cuenta remitente:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 100, -1, -1));

        add(cuentaRemitente, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 190, -1));
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 125, 190, 10));

        jLabel8.setText("Concepto:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 200, -1, -1));

        concepto.setBorder(null);
        add(concepto, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 310, -1));
        add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 310, 10));

        cuentaDestinataria.setBorder(null);
        add(cuentaDestinataria, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 190, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void botonRealizarTransferenciaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRealizarTransferenciaMousePressed
        try {
            //comprobamos que la cantidad sea un valor numerico
            double numCantidad = Double.parseDouble(cantidad.getText());
            if (!concepto.getText().isBlank() && !cantidad.getText().isBlank()) {
                Pattern pattern  = Pattern.compile("^([A-Za-z]{2}[0-9]{2} [0-9]{4} [0-9]{2} [0-9]{10})$");
                Matcher matcher = pattern.matcher(cuentaDestinataria.getText());
                if (!cuentaDestinataria.getText().isBlank() && matcher.find()) {
                    //mandamos la opcion seleccionada
                    oos.writeObject(3);
                    String ncuentaremitente = cuentaRemitente.getSelectedItem().toString();
                    Transferencia transferencia = new Transferencia(ncuentaremitente, cuentaDestinataria.getText(), concepto.getText(), numCantidad, fecha.getText());
                    ByteArrayOutputStream bos = new ByteArrayOutputStream();
                    ObjectOutputStream oosbytes = new ObjectOutputStream(bos);
                    oosbytes.writeObject(transferencia);
                    oosbytes.flush();
                    byte[] transferenciabytes = bos.toByteArray();
                    Cipher desCipher = Cipher.getInstance("DES");
                    //configuramos modo encriptar y ciframos
                    desCipher.init(Cipher.ENCRYPT_MODE, key);
                    byte[] transferenciaCifrado = desCipher.doFinal(transferenciabytes);
                    //enviamos objeto cifrado
                    oos.writeObject(transferenciaCifrado);
                    CodigoSeguridad frame = new CodigoSeguridad(panel, ois, oos, key);
                    frame.setSize(830, 550);
                    frame.setLocation(0, 0);
                    panel.removeAll();
                    panel.add(frame, BorderLayout.CENTER);
                    panel.revalidate();
                    panel.repaint();
                    JFrame telefono = new Telefono(ois, oos, key);
                    telefono.setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(null, "El número de cuenta debe escribirse como en este ejemplo: AA00 0000 00 0000000000");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Debes rellenar todos los datos");
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "La cantidad debe ser un valor numerico");
        } catch (IOException | BadPaddingException | IllegalBlockSizeException | NoSuchPaddingException ex) {
            JOptionPane.showMessageDialog(null, "Ha surgido un error inesperado");
        } catch (NoSuchAlgorithmException ex) {
            JOptionPane.showMessageDialog(null, "No se ha especificado el algoritmo");
        } catch (InvalidKeyException ex) {
            JOptionPane.showMessageDialog(null, "La llave no es correcta");
        }
    }//GEN-LAST:event_botonRealizarTransferenciaMousePressed

    private void botonLimpiarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonLimpiarMousePressed
        concepto.setText("");
        cantidad.setText("");
    }//GEN-LAST:event_botonLimpiarMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel botonLimpiar;
    private javax.swing.JPanel botonRealizarTransferencia;
    private javax.swing.JTextField cantidad;
    private javax.swing.JTextField concepto;
    private javax.swing.JTextField cuentaDestinataria;
    private javax.swing.JComboBox<String> cuentaRemitente;
    private javax.swing.JTextField fecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    // End of variables declaration//GEN-END:variables
}
