/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package swing;

import clases.NuevoCliente;

import java.awt.BorderLayout;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.security.*;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.crypto.*;
import javax.swing.*;

/**
 *
 * @author leiii
 */
public class RegistrarUsuario extends javax.swing.JPanel {
    JPanel pane;
    static JFrame ventana = new Login();

    ObjectOutputStream oos;
    ObjectInputStream ois;
    SecretKey key;
    private boolean check;
    /**
     * Creates new form RegistrarUsuario
     */
    public RegistrarUsuario(JPanel pane, JFrame ventana, ObjectOutputStream oos, ObjectInputStream ois, SecretKey key) {
        initComponents();
        this.oos = oos;
        this.ois = ois;
        this.key = key;
        this.pane = pane;
        this.ventana = ventana;

        try {
            oos.writeObject(3);
            byte[] firma = (byte[]) ois.readObject();
            PublicKey clavepub = (PublicKey) ois.readObject();
            Signature verificarsa = Signature.getInstance("SHA1WITHRSA");
            verificarsa.initVerify(clavepub);
            check = verificarsa.verify(firma);
            if (check) {
                JOptionPane.showMessageDialog(null, "El documento se ha firmado digitalmente");
            } else {
                JOptionPane.showMessageDialog(null, "El documento firmado no concide");
            }
        } catch (IOException e) {
            throw new RuntimeException(e);
        } catch (ClassNotFoundException e) {
            throw new RuntimeException(e);
        } catch (NoSuchAlgorithmException e) {
            throw new RuntimeException(e);
        } catch (InvalidKeyException e) {
            throw new RuntimeException(e);
        } catch (SignatureException e) {
            throw new RuntimeException(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        apellido = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        botonCancelar = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        botonRegistrarse = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        edad = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        email = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        usuario = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        contrasena = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        nombre = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        contrasenaRepetida = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("REGISTRO");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel2.setText("Apellido:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        apellido.setBorder(null);
        jPanel1.add(apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 240, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 240, 10));

        botonCancelar.setBackground(new java.awt.Color(153, 0, 102));
        botonCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonCancelarMousePressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Cancelar");

        javax.swing.GroupLayout botonCancelarLayout = new javax.swing.GroupLayout(botonCancelar);
        botonCancelar.setLayout(botonCancelarLayout);
        botonCancelarLayout.setHorizontalGroup(
            botonCancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botonCancelarLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel4)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        botonCancelarLayout.setVerticalGroup(
            botonCancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botonCancelarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(botonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, 120, 30));

        botonRegistrarse.setBackground(new java.awt.Color(153, 0, 102));
        botonRegistrarse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonRegistrarseMousePressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Registrarse");

        javax.swing.GroupLayout botonRegistrarseLayout = new javax.swing.GroupLayout(botonRegistrarse);
        botonRegistrarse.setLayout(botonRegistrarseLayout);
        botonRegistrarseLayout.setHorizontalGroup(
            botonRegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botonRegistrarseLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(20, 20, 20))
        );
        botonRegistrarseLayout.setVerticalGroup(
            botonRegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botonRegistrarseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(botonRegistrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 380, 120, 30));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 240, 10));

        edad.setBorder(null);
        jPanel1.add(edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 240, -1));

        jLabel6.setText("Edad:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 240, 10));

        email.setBorder(null);
        jPanel1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 240, -1));

        jLabel7.setText("Email:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 240, 10));

        usuario.setBorder(null);
        jPanel1.add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 240, -1));

        jLabel8.setText("Usuario:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 240, 10));

        contrasena.setBorder(null);
        jPanel1.add(contrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 240, -1));

        jLabel9.setText("Contraseña:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 240, 10));

        nombre.setBorder(null);
        jPanel1.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 240, -1));

        jLabel10.setText("Nombre:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jLabel11.setText("Repetir contraseña:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));

        contrasenaRepetida.setBorder(null);
        jPanel1.add(contrasenaRepetida, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, 240, -1));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, 240, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botonCancelarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCancelarMousePressed
        InicioSesion frame = new InicioSesion(pane, ventana, oos, ois, key);
        frame.setSize(490,450);
        frame.setLocation(0,0);
        
        pane.removeAll();
        pane.add(frame, BorderLayout.CENTER);
        pane.revalidate();
        pane.repaint();
    }//GEN-LAST:event_botonCancelarMousePressed

    private void botonRegistrarseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegistrarseMousePressed
        //comrovamos que ha acceptado los terminos con firma digital
        if (checkTerminos.isSelected() && check) {
            try {
                //creamos pattern para que escriba la primera letra de el nombre y apellido en mayus
                int numEdad = Integer.parseInt(edad.getText());
                Pattern mayus = Pattern.compile("^([A-Z]{1}[a-z]+)$");
                if (!nombre.getText().isBlank() && !apellido.getText().isBlank() && !edad.getText().isBlank() && !email.getText().isBlank() && !usuario.getText().isBlank() && !contrasena.getText().isBlank() && !contrasenaRepetida.getText().isBlank()) {
                    if (contrasena == contrasenaRepetida){
                        Matcher mNombre = mayus.matcher(nombre.getText());
                        Matcher mApellido = mayus.matcher(apellido.getText());
                        if (mNombre.find() && mApellido.find()) {
                            //duda preguntar
                            Pattern edadp = Pattern.compile("^[0-9]{1,3}$");
                            Matcher edadmatch = edadp.matcher(edad.getText());
                            if (edadmatch.find()) {
                                //enviamos la opcion escogida
                                oos.writeObject(2);
                                //creamos un objeto con todos los datos para registrase
                                MessageDigest md = MessageDigest.getInstance("SHA");
                                byte[] contrasenaBytes = contrasena.getText().getBytes();
                                md.update(contrasenaBytes);
                                byte[] resumen = md.digest();
                                String hashContrasena = new String(resumen);
                                NuevoCliente registrarse = new NuevoCliente(nombre.getText(), apellido.getText(), numEdad, email.getText(), usuario.getText(), hashContrasena);
                                ByteArrayOutputStream bos = new ByteArrayOutputStream();
                                ObjectOutputStream oosbytes = new ObjectOutputStream(bos);
                                //lo comvertimos a bytes
                                oosbytes.writeObject(registrarse);
                                oosbytes.flush();
                                byte[] registrarsebytes = bos.toByteArray();
                                Cipher desCipher = Cipher.getInstance("DES");
                                //configuramos modo descifrar
                                desCipher.init(Cipher.ENCRYPT_MODE, key);
                                byte[] registrarseCifrado = desCipher.doFinal(registrarsebytes);
                                //enviamos objeto cifrado
                                oos.writeObject(registrarseCifrado);
                                JOptionPane.showMessageDialog(null, "Se ha registrado el nuevo cliente");
                                //Vamos al panel de inicio de sesion
                                InicioSesion frame = new InicioSesion(pane, ventana, oos, ois, key);
                                frame.setSize(490,450);
                                frame.setLocation(0,0);

                                pane.removeAll();
                                pane.add(frame, BorderLayout.CENTER);
                                pane.revalidate();
                                pane.repaint();
                            } else {
                                JOptionPane.showMessageDialog(null, "La edad puede ser de 3 dígitos como mucho");
                            }
                        } else {
                            JOptionPane.showMessageDialog(null, "Comprueba que el nombre y el apellido estan bien escritos");
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Las contraseñas deben ser iguales");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Debes rellenar todos los campos para poder registrarte");
                }
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(null, "Los datos del campo de edad no son validos");
            } catch (NoSuchPaddingException | BadPaddingException | IllegalBlockSizeException | IOException ex) {
                JOptionPane.showMessageDialog(null, "Ha surgido un error inesperado");
            } catch (NoSuchAlgorithmException ex) {
                JOptionPane.showMessageDialog(null, "No se ha especificado el algoritmo");
            } catch (InvalidKeyException ex) {
                JOptionPane.showMessageDialog(null, "La llave no es correcta");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Tienes que aceptar los terminos para poder crear una cuenta nueva");
        }
    }//GEN-LAST:event_botonRegistrarseMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellido;
    private javax.swing.JPanel botonCancelar;
    private javax.swing.JPanel botonRegistrarse;
    private javax.swing.JTextField contrasena;
    private javax.swing.JTextField contrasenaRepetida;
    private javax.swing.JTextField edad;
    private javax.swing.JTextField email;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField usuario;
    // End of variables declaration//GEN-END:variables
}
