/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package swing;

/**
 *
 * @author leiii
 */
public class Transferencias extends javax.swing.JPanel {

    /**
     * Creates new form Transferencias
     */
    public Transferencias() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonIniciarSesion = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        botonCancelar = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cuentaDestinataria = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cantidad = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        fecha = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        cuentaRemitente = new javax.swing.JComboBox<>();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        concepto = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonIniciarSesion.setBackground(new java.awt.Color(153, 0, 102));
        botonIniciarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonIniciarSesionMousePressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Realizar transferencia");

        javax.swing.GroupLayout botonIniciarSesionLayout = new javax.swing.GroupLayout(botonIniciarSesion);
        botonIniciarSesion.setLayout(botonIniciarSesionLayout);
        botonIniciarSesionLayout.setHorizontalGroup(
            botonIniciarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botonIniciarSesionLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel5)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        botonIniciarSesionLayout.setVerticalGroup(
            botonIniciarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botonIniciarSesionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap())
        );

        add(botonIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, 180, 30));

        botonCancelar.setBackground(new java.awt.Color(153, 0, 102));
        botonCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonCancelarMousePressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Cancelar");

        javax.swing.GroupLayout botonCancelarLayout = new javax.swing.GroupLayout(botonCancelar);
        botonCancelar.setLayout(botonCancelarLayout);
        botonCancelarLayout.setHorizontalGroup(
            botonCancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botonCancelarLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel6)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        botonCancelarLayout.setVerticalGroup(
            botonCancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botonCancelarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(botonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, 120, 30));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel1.setText("Cuenta destinataria:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 150, -1, -1));

        cuentaDestinataria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(cuentaDestinataria, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 190, -1));

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("TRANSFERENCIA");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, -1, -1));

        jLabel3.setText("Cantidad:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 250, -1, -1));

        cantidad.setBorder(null);
        add(cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, 170, -1));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, 190, 10));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, 170, 10));

        jLabel4.setText("Fecha:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 300, -1, -1));

        fecha.setEditable(false);
        fecha.setBackground(new java.awt.Color(255, 255, 255));
        fecha.setBorder(null);
        add(fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, 170, -1));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, 170, 10));

        jLabel7.setText("Cuenta remitente:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 100, -1, -1));

        cuentaRemitente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(cuentaRemitente, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 190, -1));
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 190, 10));

        jLabel8.setText("Concepto:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 200, -1, -1));

        concepto.setBorder(null);
        add(concepto, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 310, -1));
        add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 310, 10));
    }// </editor-fold>//GEN-END:initComponents

    private void botonIniciarSesionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonIniciarSesionMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonIniciarSesionMousePressed

    private void botonCancelarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCancelarMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonCancelarMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel botonCancelar;
    private javax.swing.JPanel botonIniciarSesion;
    private javax.swing.JTextField cantidad;
    private javax.swing.JTextField concepto;
    private javax.swing.JComboBox<String> cuentaDestinataria;
    private javax.swing.JComboBox<String> cuentaRemitente;
    private javax.swing.JTextField fecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    // End of variables declaration//GEN-END:variables
}
