/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package swing;

import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author leiii
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        
        MisCuentas frame = new MisCuentas(panelCuenta);
        frame.setSize(560,450);
        frame.setLocation(0,0);
        
        panelCuenta.removeAll();
        panelCuenta.add(frame, BorderLayout.CENTER);
        panelCuenta.revalidate();
        panelCuenta.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        botonMisCuentas = new javax.swing.JPanel();
        bordeMisCuentas = new javax.swing.JPanel();
        labelMisCuentas = new javax.swing.JLabel();
        botonTransferencias = new javax.swing.JPanel();
        bordeTransferencias = new javax.swing.JPanel();
        labelTransferencias = new javax.swing.JLabel();
        botonCerrarSesion = new javax.swing.JPanel();
        labelCerrarSesion = new javax.swing.JLabel();
        bordeCerrarSesion = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        botonMisDatos = new javax.swing.JPanel();
        bordeMisDatos = new javax.swing.JPanel();
        labelMisDatos = new javax.swing.JLabel();
        botonCrearCuenta = new javax.swing.JPanel();
        bordeCrearCuenta = new javax.swing.JPanel();
        labelCrearCuenta = new javax.swing.JLabel();
        panelCuenta = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(153, 0, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonMisCuentas.setBackground(new java.awt.Color(241, 217, 228));
        botonMisCuentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonMisCuentasMousePressed(evt);
            }
        });
        botonMisCuentas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout bordeMisCuentasLayout = new javax.swing.GroupLayout(bordeMisCuentas);
        bordeMisCuentas.setLayout(bordeMisCuentasLayout);
        bordeMisCuentasLayout.setHorizontalGroup(
            bordeMisCuentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        bordeMisCuentasLayout.setVerticalGroup(
            bordeMisCuentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        botonMisCuentas.add(bordeMisCuentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 5, 50));

        labelMisCuentas.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        labelMisCuentas.setForeground(new java.awt.Color(51, 51, 51));
        labelMisCuentas.setText("Mis Cuentas");
        botonMisCuentas.add(labelMisCuentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 17, -1, -1));

        jPanel2.add(botonMisCuentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 190, 50));

        botonTransferencias.setBackground(new java.awt.Color(153, 0, 102));
        botonTransferencias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonTransferenciasMousePressed(evt);
            }
        });
        botonTransferencias.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bordeTransferencias.setBackground(new java.awt.Color(153, 0, 102));

        javax.swing.GroupLayout bordeTransferenciasLayout = new javax.swing.GroupLayout(bordeTransferencias);
        bordeTransferencias.setLayout(bordeTransferenciasLayout);
        bordeTransferenciasLayout.setHorizontalGroup(
            bordeTransferenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        bordeTransferenciasLayout.setVerticalGroup(
            bordeTransferenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        botonTransferencias.add(bordeTransferencias, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 5, 50));

        labelTransferencias.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        labelTransferencias.setForeground(new java.awt.Color(255, 255, 255));
        labelTransferencias.setText("Realizar tranferencia");
        botonTransferencias.add(labelTransferencias, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 17, -1, -1));

        jPanel2.add(botonTransferencias, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 190, 50));

        botonCerrarSesion.setBackground(new java.awt.Color(153, 0, 102));
        botonCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonCerrarSesionMousePressed(evt);
            }
        });
        botonCerrarSesion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelCerrarSesion.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        labelCerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        labelCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/exit.png"))); // NOI18N
        labelCerrarSesion.setText("Cerrar Sesión");
        botonCerrarSesion.add(labelCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 17, -1, -1));

        bordeCerrarSesion.setBackground(new java.awt.Color(153, 0, 102));

        javax.swing.GroupLayout bordeCerrarSesionLayout = new javax.swing.GroupLayout(bordeCerrarSesion);
        bordeCerrarSesion.setLayout(bordeCerrarSesionLayout);
        bordeCerrarSesionLayout.setHorizontalGroup(
            bordeCerrarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        bordeCerrarSesionLayout.setVerticalGroup(
            bordeCerrarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        botonCerrarSesion.add(bordeCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 5, 50));

        jPanel2.add(botonCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 190, 50));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/banco_50x50.png"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 20, -1, -1));

        botonMisDatos.setBackground(new java.awt.Color(153, 0, 102));
        botonMisDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonMisDatosMousePressed(evt);
            }
        });
        botonMisDatos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bordeMisDatos.setBackground(new java.awt.Color(153, 0, 102));

        javax.swing.GroupLayout bordeMisDatosLayout = new javax.swing.GroupLayout(bordeMisDatos);
        bordeMisDatos.setLayout(bordeMisDatosLayout);
        bordeMisDatosLayout.setHorizontalGroup(
            bordeMisDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        bordeMisDatosLayout.setVerticalGroup(
            bordeMisDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        botonMisDatos.add(bordeMisDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 5, 50));

        labelMisDatos.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        labelMisDatos.setForeground(new java.awt.Color(255, 255, 255));
        labelMisDatos.setText("Mis Datos");
        botonMisDatos.add(labelMisDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 17, -1, -1));

        jPanel2.add(botonMisDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 190, 50));

        botonCrearCuenta.setBackground(new java.awt.Color(153, 0, 102));
        botonCrearCuenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonCrearCuentaMousePressed(evt);
            }
        });

        bordeCrearCuenta.setBackground(new java.awt.Color(153, 0, 102));

        javax.swing.GroupLayout bordeCrearCuentaLayout = new javax.swing.GroupLayout(bordeCrearCuenta);
        bordeCrearCuenta.setLayout(bordeCrearCuentaLayout);
        bordeCrearCuentaLayout.setHorizontalGroup(
            bordeCrearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        bordeCrearCuentaLayout.setVerticalGroup(
            bordeCrearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        labelCrearCuenta.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        labelCrearCuenta.setForeground(new java.awt.Color(255, 255, 255));
        labelCrearCuenta.setText("Crear Cuenta");

        javax.swing.GroupLayout botonCrearCuentaLayout = new javax.swing.GroupLayout(botonCrearCuenta);
        botonCrearCuenta.setLayout(botonCrearCuentaLayout);
        botonCrearCuentaLayout.setHorizontalGroup(
            botonCrearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botonCrearCuentaLayout.createSequentialGroup()
                .addComponent(bordeCrearCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelCrearCuenta)
                .addGap(0, 84, Short.MAX_VALUE))
        );
        botonCrearCuentaLayout.setVerticalGroup(
            botonCrearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botonCrearCuentaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(bordeCrearCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(botonCrearCuentaLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(labelCrearCuenta)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(botonCrearCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 190, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 450));

        panelCuenta.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelCuentaLayout = new javax.swing.GroupLayout(panelCuenta);
        panelCuenta.setLayout(panelCuentaLayout);
        panelCuentaLayout.setHorizontalGroup(
            panelCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );
        panelCuentaLayout.setVerticalGroup(
            panelCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        jPanel1.add(panelCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 560, 450));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botonMisCuentasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonMisCuentasMousePressed
        darColor(botonMisCuentas, bordeMisCuentas, labelMisCuentas);
        devolverColor(botonTransferencias, bordeTransferencias, labelTransferencias);
        devolverColor(botonCerrarSesion, bordeCerrarSesion, labelCerrarSesion);
        devolverColor(botonMisDatos, bordeMisDatos, labelMisDatos);
        devolverColor(botonCrearCuenta, bordeCrearCuenta, labelCrearCuenta);
        
        MisCuentas frame = new MisCuentas(panelCuenta);
        frame.setSize(560,450);
        frame.setLocation(0,0);
        
        panelCuenta.removeAll();
        panelCuenta.add(frame, BorderLayout.CENTER);
        panelCuenta.revalidate();
        panelCuenta.repaint();
        
    }//GEN-LAST:event_botonMisCuentasMousePressed

    private void botonTransferenciasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonTransferenciasMousePressed
        darColor(botonTransferencias, bordeTransferencias, labelTransferencias);
        devolverColor(botonMisCuentas, bordeMisCuentas, labelMisCuentas);
        devolverColor(botonCerrarSesion, bordeCerrarSesion, labelCerrarSesion);
        devolverColor(botonMisDatos, bordeMisDatos, labelMisDatos);
        devolverColor(botonCrearCuenta, bordeCrearCuenta, labelCrearCuenta);
        
        NuevaTransferencia frame = new NuevaTransferencia();
        frame.setSize(560,450);
        frame.setLocation(0,0);
        
        panelCuenta.removeAll();
        panelCuenta.add(frame, BorderLayout.CENTER);
        panelCuenta.revalidate();
        panelCuenta.repaint();
    }//GEN-LAST:event_botonTransferenciasMousePressed

    private void botonCerrarSesionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCerrarSesionMousePressed
        darColor(botonCerrarSesion, bordeCerrarSesion, labelCerrarSesion);
        devolverColor(botonMisCuentas, bordeMisCuentas, labelMisCuentas);
        devolverColor(botonTransferencias, bordeTransferencias, labelTransferencias);
        devolverColor(botonMisDatos, bordeMisDatos, labelMisDatos);
        devolverColor(botonCrearCuenta, bordeCrearCuenta, labelCrearCuenta);
        
    }//GEN-LAST:event_botonCerrarSesionMousePressed

    private void botonMisDatosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonMisDatosMousePressed
        darColor(botonMisDatos, bordeMisDatos, labelMisDatos);
        devolverColor(botonMisCuentas, bordeMisCuentas, labelMisCuentas);
        devolverColor(botonTransferencias, bordeTransferencias, labelTransferencias);
        devolverColor(botonCerrarSesion, bordeCerrarSesion, labelCerrarSesion);
        devolverColor(botonCrearCuenta, bordeCrearCuenta, labelCrearCuenta);
        
        MisDatos frame = new MisDatos();
        frame.setSize(560,450);
        frame.setLocation(0,0);
        
        panelCuenta.removeAll();
        panelCuenta.add(frame, BorderLayout.CENTER);
        panelCuenta.revalidate();
        panelCuenta.repaint();
    }//GEN-LAST:event_botonMisDatosMousePressed

    private void botonCrearCuentaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCrearCuentaMousePressed
        darColor(botonCrearCuenta, bordeCrearCuenta, labelCrearCuenta);
        devolverColor(botonMisCuentas, bordeMisCuentas, labelMisCuentas);
        devolverColor(botonTransferencias, bordeTransferencias, labelTransferencias);
        devolverColor(botonCerrarSesion, bordeCerrarSesion, labelCerrarSesion);
        devolverColor(botonMisDatos, bordeMisDatos, labelMisDatos);
        
        NuevaCuenta frame = new NuevaCuenta();
        frame.setSize(560,450);
        frame.setLocation(0,0);
        
        panelCuenta.removeAll();
        panelCuenta.add(frame, BorderLayout.CENTER);
        panelCuenta.revalidate();
        panelCuenta.repaint();
    }//GEN-LAST:event_botonCrearCuentaMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }
    
    private void darColor(JPanel pane, JPanel borde, JLabel label) {
        pane.setBackground(new Color(241, 217, 228));
        borde.setBackground(new Color(255,255,255));
        label.setForeground(new Color(51, 51, 51));
    }
    
    private void devolverColor(JPanel pane, JPanel borde, JLabel label) {
        pane.setBackground(new Color(153, 0, 102));
        borde.setBackground(new Color(153, 0, 102));
        label.setForeground(Color.WHITE);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bordeCerrarSesion;
    private javax.swing.JPanel bordeCrearCuenta;
    private javax.swing.JPanel bordeMisCuentas;
    private javax.swing.JPanel bordeMisDatos;
    private javax.swing.JPanel bordeTransferencias;
    private javax.swing.JPanel botonCerrarSesion;
    private javax.swing.JPanel botonCrearCuenta;
    private javax.swing.JPanel botonMisCuentas;
    private javax.swing.JPanel botonMisDatos;
    private javax.swing.JPanel botonTransferencias;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelCerrarSesion;
    private javax.swing.JLabel labelCrearCuenta;
    private javax.swing.JLabel labelMisCuentas;
    private javax.swing.JLabel labelMisDatos;
    private javax.swing.JLabel labelTransferencias;
    private javax.swing.JPanel panelCuenta;
    // End of variables declaration//GEN-END:variables
}
